import _messages from './node/messages/messages_pb.cjs';
import _driverService from './node/driver_service/service_grpc_pb.cjs';
export declare const messages: {
    ObjectValue: typeof _messages.ObjectValue;
    ArrayValue: typeof _messages.ArrayValue;
    Value: typeof _messages.Value;
    Error: typeof _messages.Error;
    Function: typeof _messages.Function;
    TypeRef: typeof _messages.TypeRef;
    ResponsePath: typeof _messages.ResponsePath;
    Variable: typeof _messages.Variable;
    VariableDefinition: typeof _messages.VariableDefinition;
    Directive: typeof _messages.Directive;
    FragmentDefinition: typeof _messages.FragmentDefinition;
    Selection: typeof _messages.Selection;
    OperationDefinition: typeof _messages.OperationDefinition;
    FieldResolveInfo: typeof _messages.FieldResolveInfo;
    FieldResolveRequest: typeof _messages.FieldResolveRequest;
    FieldResolveResponse: typeof _messages.FieldResolveResponse;
    InterfaceResolveTypeInfo: typeof _messages.InterfaceResolveTypeInfo;
    InterfaceResolveTypeRequest: typeof _messages.InterfaceResolveTypeRequest;
    InterfaceResolveTypeResponse: typeof _messages.InterfaceResolveTypeResponse;
    ScalarParseRequest: typeof _messages.ScalarParseRequest;
    ScalarParseResponse: typeof _messages.ScalarParseResponse;
    ScalarSerializeRequest: typeof _messages.ScalarSerializeRequest;
    ScalarSerializeResponse: typeof _messages.ScalarSerializeResponse;
    UnionResolveTypeInfo: typeof _messages.UnionResolveTypeInfo;
    UnionResolveTypeRequest: typeof _messages.UnionResolveTypeRequest;
    UnionResolveTypeResponse: typeof _messages.UnionResolveTypeResponse;
    Secret: typeof _messages.Secret;
    SetSecretsRequest: typeof _messages.SetSecretsRequest;
    SetSecretsResponse: typeof _messages.SetSecretsResponse;
    StreamInfo: typeof _messages.StreamInfo;
    StreamRequest: typeof _messages.StreamRequest;
    StreamMessage: typeof _messages.StreamMessage;
    ByteStreamRequest: typeof _messages.ByteStreamRequest;
    ByteStream: typeof _messages.ByteStream;
    SubscriptionConnectionRequest: typeof _messages.SubscriptionConnectionRequest;
    SubscriptionConnectionResponse: typeof _messages.SubscriptionConnectionResponse;
    SubscriptionListenRequest: typeof _messages.SubscriptionListenRequest;
    SubscriptionListenMessage: typeof _messages.SubscriptionListenMessage;
};
export declare const driverService: {
    DriverService: _driverService.IDriverService;
    DriverClient: typeof _driverService.DriverClient;
};
